version: '3.1'

services:
  crud_server:
    build: ./crud_server_app
    restart: always
    env_file:
      - ./crud_server_app/.env
    ports:
      - 80:8765
    volumes:
      - ./crud_server_app:/app



